/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        nemesis: {
          bg: '#05070c',
          hull: '#0e1420',
          metal: '#1a2333',
          border: '#2a3b54',
          neon: '#00f0ff',
          alert: '#ff003c',
          fire: '#ff5500',
          slime: '#00ff66',
          warning: '#ffb700',
        },
      },
      keyframes: {
        'board-scan': {
          '0%': { top: '0%', opacity: '0' },
          '8%': { opacity: '0.55' },
          '85%': { opacity: '0.5' },
          '100%': { top: '100%', opacity: '0' },
        },
        'board-breathe': {
          '0%, 100%': { opacity: '0.55' },
          '50%': { opacity: '1' },
        },
        'board-section-in': {
          '0%': { opacity: '0', transform: 'translateY(14px) scale(0.985)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'board-delta-added': {
          '0%': { opacity: '0', transform: 'scale(0.94)' },
          '30%': { opacity: '1', transform: 'scale(1.03)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'board-delta-removed': {
          '0%': { opacity: '1' },
          '25%': { opacity: '0.25' },
          '70%': { opacity: '0.55' },
          '100%': { opacity: '1' },
        },
        'board-heartbeat': {
          '0%': { opacity: '0.15', transform: 'scaleX(0.12)' },
          '12%': { opacity: '0.9', transform: 'scaleX(0.55)' },
          '20%': { opacity: '0.3', transform: 'scaleX(0.65)' },
          '30%': { opacity: '0.95', transform: 'scaleX(1)' },
          '45%': { opacity: '0.25' },
          '100%': { opacity: '0.15', transform: 'scaleX(1)' },
        },
        'board-egg-pulse': {
          '0%, 100%': { transform: 'scale(1)', filter: 'brightness(1)' },
          '50%': { transform: 'scale(1.07)', filter: 'brightness(1.35)' },
        },
      },
      animation: {
        'board-scan': 'board-scan 5.5s ease-in-out both',
        'board-breathe': 'board-breathe 6s ease-in-out infinite',
        'board-section-in': 'board-section-in 420ms ease-out both',
        'board-delta-added': 'board-delta-added 900ms ease-out both',
        'board-delta-removed': 'board-delta-removed 1200ms ease-out both',
        'board-heartbeat': 'board-heartbeat 1.9s ease-in-out infinite',
        'board-egg-pulse': 'board-egg-pulse 2.6s ease-in-out infinite',
        'contact-reveal': {
          '0%': { opacity: '0', transform: 'perspective(600px) translateY(48px) rotateY(180deg) scale(0.65)' },
          '60%': { opacity: '1', transform: 'perspective(600px) translateY(-6px) rotateY(15deg) scale(1.05)' },
          '100%': { opacity: '1', transform: 'perspective(600px) translateY(0) rotateY(0) scale(1)' },
        },
        'contact-warning': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.65' },
        },
        'contact-card': {
          '0%': { opacity: '0', transform: 'translateY(18px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'die-roll': {
          '0%': { transform: 'rotate(-160deg) scale(0.7)', opacity: '0' },
          '55%': { transform: 'rotate(12deg) scale(1.08)', opacity: '1' },
          '75%': { transform: 'rotate(-6deg) scale(0.98)' },
          '100%': { transform: 'rotate(0deg) scale(1)', opacity: '1' },
        },
        'vent-alarm': {
          '0%, 100%': { opacity: '0.85' },
          '50%': { opacity: '0.25' },
        },
        'vent-flow': {
          '0%': { strokeDashoffset: '0' },
          '100%': { strokeDashoffset: '-24' },
        },
        'vent-echo': {
          '0%': { opacity: '0', transform: 'translateY(6px) scale(0.55)' },
          '14%': { opacity: '0.95', transform: 'translateY(0) scale(1)' },
          '65%': { opacity: '0.5', transform: 'translateY(-3px) scale(0.92)' },
          '100%': { opacity: '0', transform: 'translateY(9px) scale(0.4)' },
        },
        'door-breach': {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '18%': { opacity: '1', transform: 'scale(1.25)' },
          '38%': { opacity: '0.9', transform: 'scale(0.92)' },
          '55%': { opacity: '1', transform: 'scale(1.12)' },
          '100%': { opacity: '0', transform: 'scale(1.6)' },
        },
        'token-fade': {
          '0%': { opacity: '0' },
          '30%': { opacity: '1' },
          '100%': { opacity: '1' },
        },
        'modal-enter': {
          '0%': { opacity: '0', transform: 'translateY(18px) scale(0.97)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1)' },
        },
        'step-enter': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'gauge-flash': {
          '0%': { opacity: '0.2' },
          '40%': { opacity: '1' },
          '100%': { opacity: '1' },
        },
        'card-reveal': {
          '0%': { opacity: '0', transform: 'translateY(14px) scale(0.92) rotate(-1.5deg)' },
          '60%': { opacity: '1', transform: 'translateY(-3px) scale(1.02) rotate(0.5deg)' },
          '100%': { opacity: '1', transform: 'translateY(0) scale(1) rotate(0)' },
        },
        'flame-flicker': {
          '0%, 100%': { opacity: '0.95', transform: 'scale(1)' },
          '30%': { opacity: '0.7', transform: 'scale(1.06)' },
          '60%': { opacity: '1', transform: 'scale(0.97)' },
        },
        'token-pop': {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '60%': { opacity: '1', transform: 'scale(1.18)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'door-shockwave': {
          '0%': { opacity: '0.9', transform: 'scale(0.15)' },
          '100%': { opacity: '0', transform: 'scale(2.4)' },
        },
        'door-spark': {
          '0%': { opacity: '0', transform: 'scaleY(0.2)' },
          '25%': { opacity: '1', transform: 'scaleY(1.1)' },
          '100%': { opacity: '0', transform: 'scaleY(0.4)' },
        },
        'hub-ripple': {
          '0%': { opacity: '0', transform: 'scale(0.25)' },
          '35%': { opacity: '0.75', transform: 'scale(0.8)' },
          '100%': { opacity: '0', transform: 'scale(1.7)' },
        },
        'fog-dissolve': {
          '0%': { opacity: '1', transform: 'scale(1)', filter: 'blur(0px)' },
          '20%': { opacity: '0.85', transform: 'scale(1.02)', filter: 'blur(0.5px)' },
          '55%': { opacity: '0.35', transform: 'scale(1.08)', filter: 'blur(2px)' },
          '100%': { opacity: '0', transform: 'scale(1.15)', filter: 'blur(6px)' },
        },
        'fog-idle': {
          '0%, 100%': { opacity: '0.92', transform: 'scale(1) translate(0,0)' },
          '50%': { opacity: '1', transform: 'scale(1.015) translate(0.3px, -0.4px)' },
        },
        'fog-drift': {
          '0%': { transform: 'translate(0,0) scale(1)' },
          '33%': { transform: 'translate(1.2px, -0.8px) scale(1.02)' },
          '66%': { transform: 'translate(-0.9px, 0.6px) scale(0.98)' },
          '100%': { transform: 'translate(0,0) scale(1)' },
        },
        'fog-pulse': {
          '0%, 100%': { opacity: '0.52' },
          '50%': { opacity: '0.68' },
        },
        'scanline-sweep': {
          '0%': { transform: 'translateX(-78px)', opacity: '0' },
          '12%': { opacity: '0.9' },
          '45%': { opacity: '1' },
          '75%': { opacity: '0.85' },
          '100%': { transform: 'translateX(78px)', opacity: '0' },
        },
        'room-flip': {
          '0%': { transform: 'scaleY(1) scaleX(1)', filter: 'brightness(1)' },
          '38%': { transform: 'scaleY(0.08) scaleX(1.04)', filter: 'brightness(1.6)' },
          '62%': { transform: 'scaleY(0.08) scaleX(1.04)', filter: 'brightness(1.6)' },
          '100%': { transform: 'scaleY(1) scaleX(1)', filter: 'brightness(1)' },
        },
        'room-flash': {
          '0%': { strokeWidth: '1.5', strokeOpacity: '0', opacity: '0' },
          '22%': { strokeWidth: '8', strokeOpacity: '1', opacity: '1' },
          '58%': { strokeWidth: '5', strokeOpacity: '0.9', opacity: '1' },
          '100%': { strokeWidth: '1.5', strokeOpacity: '0', opacity: '0' },
        },
        'typewriter-cursor': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0' },
        },
        'room-icon-pop': {
          '0%': { opacity: '0', transform: 'scale(0.2) translateY(6px)' },
          '55%': { opacity: '1', transform: 'scale(1.25) translateY(-2px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        'exploration-reveal': {
          '0%': { opacity: '0', transform: 'translateY(18px) scale(0.32) rotate(-3deg)' },
          '22%': { opacity: '1', transform: 'translateY(-6px) scale(1.18) rotate(1deg)' },
          '36%': { opacity: '1', transform: 'translateY(0) scale(1) rotate(0)' },
          '78%': { opacity: '1', transform: 'translateY(0) scale(1) rotate(0)' },
          '100%': { opacity: '0', transform: 'translateY(-14px) scale(0.88)' },
        },
        'exploration-settle': {
          '0%': { opacity: '1', transform: 'translateY(0) scale(1)' },
          '100%': { opacity: '0', transform: 'translateY(10px) scale(0.82)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-2px)' },
          '75%': { transform: 'translateX(2px)' },
        },
        'noise-ripple': {
          '0%': { opacity: '0', transform: 'scale(0.25)' },
          '35%': { opacity: '0.75', transform: 'scale(0.8)' },
          '100%': { opacity: '0', transform: 'scale(1.7)' },
        },
        'noise-flash': {
          '0%': { opacity: '0.9', transform: 'scale(0.2)', strokeWidth: '2' },
          '40%': { opacity: '0.85', transform: 'scale(1.15)', strokeWidth: '4.5' },
          '100%': { opacity: '0', transform: 'scale(1.9)', strokeWidth: '1' },
        },
        'contact-vignette': {
          '0%': { opacity: '0' },
          '18%': { opacity: '1' },
          '72%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'stars-twinkle-1': {
          '0%, 100%': { opacity: '0.9' },
          '50%': { opacity: '0.45' },
        },
        'stars-twinkle-2': {
          '0%, 100%': { opacity: '0.85' },
          '33%': { opacity: '0.35' },
          '66%': { opacity: '0.95' },
        },
        'stars-twinkle-3': {
          '0%, 100%': { opacity: '0.75' },
          '25%': { opacity: '0.3' },
          '75%': { opacity: '1' },
        },
        'stars-drift-1': {
          '0%': { transform: 'translate(0,0)' },
          '100%': { transform: 'translate(-8px, 4px)' },
        },
        'stars-drift-2': {
          '0%': { transform: 'translate(0,0)' },
          '100%': { transform: 'translate(6px, -6px)' },
        },
        'stars-drift-3': {
          '0%': { transform: 'translate(0,0)' },
          '100%': { transform: 'translate(-4px, -8px)' },
        },
      },
      animation: {
        'contact-reveal': 'contact-reveal 800ms ease-out both',
        'contact-warning': 'contact-warning 700ms ease-in-out 2',
        'contact-card': 'contact-card 450ms ease-out both',
        'die-roll': 'die-roll 900ms ease-out both',
        'vent-alarm': 'vent-alarm 1.1s ease-in-out infinite',
        'vent-flow': 'vent-flow 1.6s linear infinite',
        'vent-echo': 'vent-echo 2400ms ease-in-out both',
        'door-breach': 'door-breach 1s ease-out both',
        'token-fade': 'token-fade 700ms ease-out both',
        'modal-enter': 'modal-enter 500ms cubic-bezier(0.22, 0.9, 0.3, 1) both',
        'step-enter': 'step-enter 380ms ease-out both',
        'gauge-flash': 'gauge-flash 900ms ease-out both',
        'card-reveal': 'card-reveal 650ms cubic-bezier(0.3, 0.8, 0.3, 1) both',
        'flame-flicker': 'flame-flicker 1.4s ease-in-out 3',
        'token-pop': 'token-pop 700ms cubic-bezier(0.34, 1.4, 0.5, 1) both',
        'door-shockwave': 'door-shockwave 900ms ease-out both',
        'door-spark': 'door-spark 750ms ease-out both',
        'hub-ripple': 'hub-ripple 1100ms ease-out 450ms both',
        'fog-dissolve': 'fog-dissolve 720ms cubic-bezier(0.4, 0, 0.2, 1) both',
        'fog-idle': 'fog-idle 4.2s ease-in-out infinite',
        'fog-drift': 'fog-drift 6.5s ease-in-out infinite',
        'fog-pulse': 'fog-pulse 3.8s ease-in-out infinite',
        'scanline-sweep': 'scanline-sweep 820ms cubic-bezier(0.22, 0.9, 0.3, 1) both',
        'room-flip': 'room-flip 520ms cubic-bezier(0.6, 0, 0.4, 1) both',
        'room-flash': 'room-flash 680ms ease-out both',
        'room-icon-pop': 'room-icon-pop 520ms cubic-bezier(0.34, 1.4, 0.5, 1) both',
        'typewriter-cursor': 'typewriter-cursor 750ms step-end infinite',
        'exploration-reveal': 'exploration-reveal 1650ms cubic-bezier(0.34, 1.2, 0.5, 1) both',
        shake: 'shake 0.4s ease-in-out both',
        'noise-ripple': 'noise-ripple 900ms ease-out both',
        'noise-flash': 'noise-flash 700ms ease-out both',
        'contact-vignette': 'contact-vignette 1600ms ease-out both',
        'stars-twinkle-1': 'stars-twinkle-1 3.2s ease-in-out infinite',
        'stars-twinkle-2': 'stars-twinkle-2 5.1s ease-in-out infinite',
        'stars-twinkle-3': 'stars-twinkle-3 4.3s ease-in-out infinite',
        'stars-drift-1': 'stars-drift-1 120s linear infinite alternate',
        'stars-drift-2': 'stars-drift-2 180s linear infinite alternate',
        'stars-drift-3': 'stars-drift-3 240s linear infinite alternate',
      },
      boxShadow: {
        'neon-cyan': '0 0 15px rgba(0, 240, 255, 0.4)',
        'neon-red': '0 0 15px rgba(255, 0, 60, 0.5)',
      },
    },
  },
  plugins: [],
};
