export const CARD_OPTION = {
  FIX_ROOM: 'FIX_ROOM',
  ENGINE_REPAIR: 'ENGINE_REPAIR',
  ENGINE_DAMAGE: 'ENGINE_DAMAGE',
  DOOR: 'DOOR',
  PEEK: 'PEEK',
  MALFUNCTION: 'MALFUNCTION',
  EXTINGUISH: 'EXTINGUISH',
  PLACE_FIRE: 'PLACE_FIRE',
  CRAFT: 'CRAFT',
  ROOM_ACTION: 'ROOM_ACTION',
  KEEP_TOP: 'KEEP_TOP',
  MOVE_BOTTOM: 'MOVE_BOTTOM',
  CHARGE: 'CHARGE',
  RETREAT: 'RETREAT',
  TREAT_SERIOUS: 'TREAT_SERIOUS',
  HEAL_LIGHT: 'HEAL_LIGHT',
  HEAL_TREATED: 'HEAL_TREATED',
  SLIME: 'SLIME',
  COMBINE_HEAVY: 'COMBINE_HEAVY',
  STUN_INTRUDER: 'STUN_INTRUDER',
  DISARM_CHARACTER: 'DISARM_CHARACTER',
} as const;

export type CardOption = (typeof CARD_OPTION)[keyof typeof CARD_OPTION];

export const ENGINE_OPTIONS: readonly CardOption[] = [CARD_OPTION.ENGINE_REPAIR, CARD_OPTION.ENGINE_DAMAGE];
